115 long running queries
icatproject/ids.server pull request #118
Opened 2021-03-15 14:22 UTC by kevinphippsstfc

Closes #115 

The solution is based around the use of the reader account (already used by the Tidier etc. in the IDS) and a new property useReaderForPerformance which must be set for this to be used. In addition, there must be a PublicStep defined from Dataset to datafiles, which then allows use of the reader account for doing the expensive Datafiles queries once it has been confirmed that the user has access to the parent Dataset.

If the property is not set or the PublicStep does not exist then the behaviour will be as before, with the user's session used to lookup both the Datasets and the Datafiles.

2021-03-19 15:34 UTC, RKrahl requested changes
Many thanks for submitting this! I tested it and it works fine. Overall, I'm happy with the changes.

I left some comments on minor issues.  Most importantly, I suggest dropping the check for the `PublicStep` which would also simplify things, but would also require amending the documentation.

2021-03-19 15:34 UTC, RKrahl commented on src/test/resources/test.properties
> +login.root = db username root password password
Appreciate this tidying up!

2021-03-19 15:34 UTC, RKrahl commented on src/test/java/org/icatproject/ids/IcatReaderTest.java
> +        assertNotNull("An ICAT session ID was expected", icatReader.getSessionId());
This requires the user `reader` to be added in the authentication plugin. Until now, the documentation on how to run the tests refer to the corresponding documentation for `icat.server` which in turn instructs to add the users `notroot`, `piOne`, `piTwo`, `root`, `guest`, and `CIC`.

2021-03-19 15:34 UTC, RKrahl commented on src/site/xhtml/installation.xhtml.vm
> +
If we drop the check on `PublicStep` as suggested in the comment in `IcatReader.java` we would need to change that comment here that setting `useReaderForPerformance` will effectively imply a public step.

2021-03-23 15:01 UTC, kevinphippsstfc commented on pom.xml
> +
Thanks for spotting this. I've now upgraded to the current version and there are some minor code changes to go with that. Sorry but I don't know about using Mockito with JUnit 4 vs JUnit 5.

2021-03-23 15:10 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/ids/PropertyHandler.java
> +
OK, I've added that.

2021-04-06 15:51 UTC, RKrahl approved these changes

2021-04-06 15:57 UTC, RKrahl commented
Looks good for me now.  @stuartpullinger: do you still want to have a look before merging?

2021-04-12 06:43 UTC, merged